<a href="https://colab.research.google.com/github/Chaqmoqjon/Machine-Learning/blob/main/3_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

##Datani tayyorlash

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
from sklearn.model_selection import train_test_split
train_set, test_set =  train_test_split(df, test_size= 0.2, random_state  = 42)

In [ ]:
housing = train_set.drop('median_house_value', axis = 1) #parametrlar: "bashorat" qiluvchilar
housing_labels = train_set['median_house_value'].copy() #labels: topishimiz kerak bo'lgan qiymatlar

In [ ]:
df.info() #total_bedrooms ustunida NaN qiymatlar borligi aniqlandi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [ ]:
#1. NaN bor qatorlarni tashlab yuborish. Bir nechta ma'lumotlar yo'q bo'lsa foydali
df.dropna(subset = ['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [ ]:
#2. NaN qiymati bor ustunni tashlab yuborish. 80% - 90% ma'lumot yo'q bo'lsa foydali
df.drop('total_bedrooms', axis = 1)

longitude  latitude  housing_median_age  total_rooms  population  \
0        -122.23     37.88                41.0        880.0       322.0   
1        -122.22     37.86                21.0       7099.0      2401.0   
2        -122.24     37.85                52.0       1467.0       496.0   
3        -122.25     37.85                52.0       1274.0       558.0   
4        -122.25     37.85                52.0       1627.0       565.0   
...          ...       ...                 ...          ...         ...   
20635    -121.09     39.48                25.0       1665.0       845.0   
20636    -121.21     39.49                18.0        697.0       356.0   
20637    -121.22     39.43                17.0       2254.0      1007.0   
20638    -121.32     39.43                18.0       1860.0       741.0   
20639    -121.24     39.37                16.0       2785.0      1387.0   

       households  median_income  median_house_value ocean_proximity  
0           126.0         8.3252            452600.0        NEAR BAY  
1          1138.0         8.3014            358500.0        NEAR BAY  
2           177.0         7.2574            352100.0        NEAR BAY  
3           219.0         5.6431            341300.0        NEAR BAY  
4           259.0         3.8462            342200.0        NEAR BAY  
...           ...            ...                 ...             ...  
20635       330.0         1.5603             78100.0          INLAND  
20636       114.0         2.5568             77100.0          INLAND  
20637       433.0         1.7000             92300.0          INLAND  
20638       349.0         1.8672             84700.0          INLAND  
20639       530.0         2.3886             89400.0          INLAND  

[20640 rows x 9 columns]

In [ ]:
#NaN qiymatlarni, boshqa qiymat bilan to'ldirish. 10% atrofida ma'lumot yo'q bo'lsa foydali
median = df['total_bedrooms'].median()
df['total_bedrooms'] = df['total_bedrooms'].fillna(median)

#**TRANSFORMERS**
Simple Imputer, Ordinal Encoder, One Hot Encoder, Custom Transformer, Min Max Scalar, Standart Scalar

##Simple Imputer
Aytilgan qiymat bilan to'ldirish (median, mean)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median') #har bir ustun uchun median hisoblaydi

In [ ]:
housing_num = housing.drop('ocean_proximity', axis = 1) #string bo'lganlligi uchun tashlab yuborildi

In [ ]:
imputer.fit(housing_num) #faqat hisoblaydi

SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_ #qiymatlarni ko'rish

array([-118.51  ,   34.26  ,   29.    , 2129.    ,  437.    , 1167.    ,
        410.    ,    3.5458])

In [ ]:
X = imputer.transform(housing_num) #qiymatlarni joylash
X #type: np array

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

In [ ]:
X = imputer.fit_transform(housing_num) #fit va transformni bittada
X #type: np array

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

In [ ]:
housing_tr = pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index) #df ga aylantirish
housing_tr.head() #NaN qiymatlar median bilan to'ldirildi

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542

In [ ]:
housing_cat = housing[['ocean_proximity']] #raqamli qiymatga o'tkazish uchun
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7341
INLAND             5227
NEAR OCEAN         2086
NEAR BAY           1854
ISLAND                4
Name: count, dtype: int64

##Ordinal Encoder.
Tartiblangan qiymatlar

In [ ]:
from IPython.core.display import display, HTML

display(HTML('<img src="https://miro.medium.com/v2/resize:fit:654/1*NUzgzszTdpLPZpeKPPf0kQ.png" alt="" width="600" />'))

In [ ]:
from sklearn.preprocessing import OrdinalEncoder #tartiblangan qiymatga aylantiradi
ordinal_encoder = OrdinalEncoder()

In [ ]:
housing_cat_encoder = ordinal_encoder.fit_transform(housing_cat) #housing_cat ni tartibli raqamga aylantir
housing_cat_encoder[:10]

array([[4.],
       [4.],
       [4.],
       [4.],
       [1.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.]])

In [ ]:
housing.head(10)    #housing_cat_encoder[:10] va housing.head(10) mantiqan bir-biriga to'g'ri kelmaydi.  OrdinalEncoder yechimi to'g'ri kelmaydi!

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
17848    -121.86     37.42                20.0       5032.0           808.0   
6252     -117.97     34.04                28.0       1686.0           417.0   
9389     -122.53     37.91                37.0       2524.0           398.0   
6113     -117.90     34.13                 5.0       1126.0           316.0   
6061     -117.79     34.02                 5.0      18690.0          2862.0   

       population  households  median_income ocean_proximity  
14196      2300.0       623.0         3.2596      NEAR OCEAN  
8267       1314.0       756.0         3.8125      NEAR OCEAN  
17445       915.0       336.0         4.1563      NEAR OCEAN  
14265      1418.0       355.0         1.9425      NEAR OCEAN  
2271        874.0       380.0         3.5542          INLAND  
17848      2695.0       801.0         6.6227       <1H OCEAN  
6252       1355.0       388.0         2.5192       <1H OCEAN  
9389        999.0       417.0         7.9892        NEAR BAY  
6113        819.0       311.0         1.5000       <1H OCEAN  
6061       9427.0      2777.0         6.4266       <1H OCEAN

##One Hot Encoder.
Yani ustunga mos ravishta bir berish

In [ ]:
from IPython.core.display import display, HTML

display(HTML('<img src="https://i.imgur.com/mtimFxh.png" alt="" width="600" />'))

In [ ]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()

In [ ]:
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray() #ustundagi har bir bo'lim uchun bir ustun yaratadi va mos ustunga 1 beradi

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
#OneHot pd bilan bajarislishi
housing_onehot = pd.get_dummies(housing['ocean_proximity']) #
housing_onehot

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
14196      False   False   False     False        True
8267       False   False   False     False        True
17445      False   False   False     False        True
14265      False   False   False     False        True
2271       False    True   False     False       False
...          ...     ...     ...       ...         ...
11284       True   False   False     False       False
11964      False    True   False     False       False
5390        True   False   False     False       False
860         True   False   False     False       False
15795      False   False   False      True       False

[16512 rows x 5 columns]

In [ ]:
housing['ocean_proximity']

14196    NEAR OCEAN
8267     NEAR OCEAN
17445    NEAR OCEAN
14265    NEAR OCEAN
2271         INLAND
            ...    
11284     <1H OCEAN
11964        INLAND
5390      <1H OCEAN
860       <1H OCEAN
15795      NEAR BAY
Name: ocean_proximity, Length: 16512, dtype: object

##Custom Transformer
Personal transformer

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin #shaxsiy transformer yasash

In [ ]:
#bizga kerak ustunlar indekslari
rooms_ix, badrooms_ix, population_ix, households_ix = 3, 4, 5, 6

In [ ]:
class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
  def __init__(self, add_bedrooms_per_room = True):
    self.add_bedrooms_per_room = add_bedrooms_per_room
  def fit(self, X, y = None):
    return self  #bizning funksiya faqat transformer, estimator emas
  def transform(self, X):
    rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
    population_per_household = X[:, population_ix] / X[:, households_ix]
    if self.add_bedrooms_per_room: #add_bedrooms_per_room ustuni ixtiyoriy bo'ladi
      bedrooms_per_room = X[:, badrooms_ix] / X[:, rooms_ix]
      return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
    else:
      return np.c_[X, rooms_per_household, population_per_household]

In [ ]:
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room = False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [ ]:
housing.values[0]

array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN'], dtype=object)

In [ ]:
housing_extra_attribs[0, :]

array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN', 5.017656500802568, 3.691813804173355], dtype=object)

##Min Max Scalar
0 va 1 ora'lig'iga olib kelish

In [ ]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20640.000000  20640.000000  20640.000000   20640.000000   
mean       536.838857   1425.476744    499.539680       3.870671   
std        419.391878   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        643.250000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [ ]:
minx = df['median_income'].min()
maxx = df['median_income'].max()
(df['median_income'] - minx) / (maxx - minx)

0        0.539668
1        0.538027
2        0.466028
3        0.354699
4        0.230776
           ...   
20635    0.073130
20636    0.141853
20637    0.082764
20638    0.094295
20639    0.130253
Name: median_income, Length: 20640, dtype: float64

In [ ]:
from IPython.core.display import display, HTML

display(HTML('<img src="https://miro.medium.com/v2/resize:fit:888/1*ye1I00S61GqpR34ABZZFLQ.png" alt="MinMaxScaler" width="600" />'))

In [ ]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler  = MinMaxScaler()

In [ ]:
min_max_scaler.fit_transform(housing_num) #faqat raqamlari bor ustun. qiymatlarni 0 va 1 oralig'ida joylashtiradi

array([[0.72908367, 0.01702128, 0.62745098, ..., 0.06437961, 0.10228581,
        0.19032151],
       [0.61653386, 0.12978723, 0.94117647, ..., 0.0367443 , 0.12415721,
        0.22845202],
       [0.38545817, 0.22446809, 0.05882353, ..., 0.02556125, 0.05508962,
        0.25216204],
       ...,
       [0.59462151, 0.15744681, 0.68627451, ..., 0.04913254, 0.08649893,
        0.16789424],
       [0.23804781, 0.53510638, 0.2745098 , ..., 0.04972112, 0.09176122,
        0.35994676],
       [0.19223108, 0.55531915, 1.        , ..., 0.07332044, 0.20407828,
        0.14314285]])

In [ ]:
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542  
...           ...         ...            ...  
11284       658.0       217.0         6.3700  
11964      1753.0       449.0         3.0500  
5390       1756.0       527.0         2.9344  
860        1777.0       559.0         5.7192  
15795      2619.0      1242.0         2.5755  

[16512 rows x 8 columns]

##Standard Scaler
Ma'lum bir oraliqga olib kelish

In [ ]:
display(HTML('<img src="https://journaldev.nyc3.cdn.digitaloceanspaces.com/2020/10/Standardization.png" alt="California" width="600" />'))

In [ ]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()

In [ ]:
standard_scaler.fit_transform(housing_num) #qiymatlarni ma'lum bir oraliqga olib keltiradi

array([[ 1.27258656, -1.3728112 ,  0.34849025, ...,  0.76827628,
         0.32290591, -0.326196  ],
       [ 0.70916212, -0.87669601,  1.61811813, ..., -0.09890135,
         0.6720272 , -0.03584338],
       [-0.44760309, -0.46014647, -1.95271028, ..., -0.44981806,
        -0.43046109,  0.14470145],
       ...,
       [ 0.59946887, -0.75500738,  0.58654547, ...,  0.28983345,
         0.07090859, -0.49697313],
       [-1.18553953,  0.90651045, -1.07984112, ...,  0.30830275,
         0.15490769,  0.96545045],
       [-1.41489815,  0.99543676,  1.85617335, ...,  1.04883375,
         1.94776365, -0.68544764]])